---
abstract: 'Time-related tests for asynchronous routines using AnyEvent'
author:
  - 'Toshio Ito <debug.ito@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-AnyEvent-Time
no_index:
  directory:
    - eg
    - t
    - inc
requires:
  AnyEvent: 7.01
  Carp: 0
  Scalar::Util: 0
  Test::Builder: 0
resources:
  repository: git://github.com/debug-ito/Test-AnyEvent-Time.git
version: 0.01
